### ISSUE TITLE
Not actually setting cookie options

### ISSUE THREAD

**Issue by oliverjam** [fac21/week7--Server-Side-App-AANS#25]
https://github.com/fac21/Week7--Server-Side-App-AANS/blob/d79730ceca03811cadceb7dbdd8643839df77c9c/server.js#L23

Your cookie options are exported as `COOKIE_OPTIONS`; `auth.COOKIE_SECRET` is undefined so the session middleware isn't actually using your options

**Comment by sevdas** [comment]
Thanks, Oli. 

#25
