### ISSUE TITLE
const flashMes

### ISSUE THREAD

**Issue by maryamgh1988** [fac21/week7--Server-Side-App-AANS#36]
I was wondering why you added flash message to the html . Is there any way to be more clear ?
because the message is going to be disappear but the content should be remained 

  const flashMes = flashMessages.getFleshMessage(request);

  response.send(templates.getHtml("Sign up", flashMes + pageContent));

**Comment by sevdas** [comment]
Thanks, Maryam for the question. We used HTML as a template and chained it to our middleware. 
Here is an article that helps us a lot getting out heads wound how exactly flash middleware works. Chaining was just an additional refactoring of us. Hope this answers your question. 

https://medium.com/@roycjh/5-minute-code-how-to-use-connect-flash-in-your-express-app-339885821937
